# Generated by Django 4.0 on 2023-03-26 09:00

from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_first_name_alter_user_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='color',
            field=models.ForeignKey(blank=True, default=users.models.Color.get_default_pk, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.color', verbose_name='цвет'),
        ),
    ]
