# Generated by Django 4.0 on 2023-03-18 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertest',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='пользователь'),
        ),
        migrations.AddField(
            model_name='usertest',
            name='testcase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.test', verbose_name='тест'),
        ),
        migrations.AddField(
            model_name='userquestionanswer',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.answer', verbose_name='ответ'),
        ),
        migrations.AddField(
            model_name='userquestionanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.question', verbose_name='вопрос'),
        ),
        migrations.AddField(
            model_name='userquestionanswer',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='пользователь'),
        ),
        migrations.AddField(
            model_name='test',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='users.user', verbose_name='автор теста'),
        ),
        migrations.AddField(
            model_name='test',
            name='subjects',
            field=models.ManyToManyField(through='core.UserTest', to=settings.AUTH_USER_MODEL, verbose_name='испытуемые'),
        ),
        migrations.AddField(
            model_name='test',
            name='theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='core.theme', verbose_name='тема'),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.answer', verbose_name='ответ'),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.question', verbose_name='вопрос'),
        ),
        migrations.AddField(
            model_name='question',
            name='answers',
            field=models.ManyToManyField(through='core.QuestionAnswer', to='core.Answer', verbose_name='ответы'),
        ),
        migrations.AddField(
            model_name='question',
            name='test_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.test', verbose_name='тесты'),
        ),
        migrations.AddConstraint(
            model_name='usertest',
            constraint=models.UniqueConstraint(fields=('subject', 'testcase'), name='unique_user_test'),
        ),
        migrations.AddConstraint(
            model_name='userquestionanswer',
            constraint=models.UniqueConstraint(fields=('question', 'answer', 'subject'), name='unique_question_subject'),
        ),
        migrations.AddConstraint(
            model_name='questionanswer',
            constraint=models.UniqueConstraint(fields=('question', 'answer'), name='unique_question_answer'),
        ),
    ]
